"""Content for every problem. Text fields may contain inline HTML."""

CATEGORIES = [
    ("number-theory", "Number theory", None),
    ("cs-logic", "Computer science and logic", None),
    ("geometry", "Geometry and combinatorics", None),
    ("numbers", "Numbers themselves", None),
    ("graph-theory", "Graph theory",
     'A <strong>graph</strong> here means a set of dots (vertices) joined by lines (edges).'),
]

PROBLEMS = [
    # ------------------------------------------------------------------ number theory
    dict(
        slug="twin-primes", cat="number-theory", pick=True,
        title="Twin Prime Conjecture",
        short="Are there infinitely many pairs of primes that differ by 2, like (3, 5), (11, 13) and (17, 19)?",
        short_status="Zhang (2013) and Maynard proved that infinitely many prime pairs differ by at most 246. The gap of 2 is still unproven.",
        statement="There are infinitely many primes <em>p</em> such that <em>p</em> + 2 is also prime.",
        facts=[("First posed", "Implicit since antiquity; stated by de Polignac, 1849"),
               ("Best result", "Infinitely many gaps ≤ 246"),
               ("Largest known pair", "388,342 digits (2016)")],
        importance=[
            "Primes are the atoms of arithmetic, and the twin prime question asks something basic about how they are spaced. The prime number theorem says the <em>average</em> gap near <em>x</em> is about ln <em>x</em>, which grows without bound. The conjecture says that, despite this, the smallest possible gap keeps recurring forever.",
            "Hardy and Littlewood made a precise prediction: the number of twin primes up to <em>x</em> should be about 1.32 · <em>x</em> / (ln <em>x</em>)². Computer counts match this prediction extremely well. Proving it would show that primes behave like random numbers in a deep, quantitative way.",
            "The problem has also driven the development of <strong>sieve methods</strong>, one of the main toolkits of analytic number theory.",
        ],
        status=[
            "Open. The breakthrough of the last decade is that <em>bounded</em> gaps are now proven: there is some fixed number <em>H</em> such that infinitely many pairs of primes differ by at most <em>H</em>. The current record is <em>H</em> = 246.",
            "Assuming a strong unproven hypothesis about how primes are spread across arithmetic progressions (the generalized Elliott–Halberstam conjecture), the bound drops to 6. Getting from 6 to 2 hits a known wall called the <strong>parity problem</strong>.",
        ],
        timeline=[
            ("1919", "Brun shows the sum of reciprocals of twin primes converges (to Brun's constant, about 1.902). So twin primes, if infinite, are very sparse. This is also where modern sieve theory begins."),
            ("1923", "Hardy and Littlewood conjecture the precise count of twin primes."),
            ("1973", "Chen proves there are infinitely many primes <em>p</em> where <em>p</em> + 2 is either prime or a product of two primes."),
            ("2005", "Goldston, Pintz and Yıldırım show prime gaps can be arbitrarily small compared with the average gap."),
            ("2013", "Yitang Zhang proves infinitely many gaps of at most 70,000,000, the first finite bound ever."),
            ("2013–14", "Maynard, and independently Tao, find a simpler, stronger sieve. The Polymath8 collaboration then brings the bound down to 246."),
            ("2016", "The largest known twin primes are found: 2996863034895 · 2<sup>1290000</sup> ± 1."),
        ],
        approaches=[
            "<strong>Beat the parity barrier.</strong> Selberg showed that classical sieves cannot tell numbers with an odd number of prime factors from those with an even number. Any proof must bring in extra information to break this symmetry. That is how Friedlander and Iwaniec proved there are infinitely many primes of the form <em>a</em>² + <em>b</em>⁴.",
            "<strong>Improve the level of distribution.</strong> Zhang's key step was to show that primes are well distributed in arithmetic progressions slightly beyond what the Bombieri–Vinogradov theorem gives. Further progress here shrinks the gap bound.",
            "<strong>Learn from the function field analogue.</strong> Sawin and Shusterman proved a version of the twin prime conjecture for polynomials over certain finite fields. Translating ideas from that setting back to the integers is an active direction.",
        ],
        try_it="List the primes up to 200 and circle every twin pair. Count how many you find in each block of 50 numbers. Do they thin out? Compare your counts with 1.32 · 50 / (ln <em>x</em>)².",
    ),
    dict(
        slug="goldbach", cat="number-theory", pick=True,
        title="Goldbach's Conjecture",
        short="Is every even number greater than 2 the sum of two primes? For example, 28 = 5 + 23.",
        short_status="Checked up to 4 × 10¹⁸ but never proven.",
        statement="Every even integer greater than 2 can be written as the sum of two primes.",
        facts=[("First posed", "Goldbach's letter to Euler, 1742"),
               ("Verified up to", "4 × 10¹⁸"),
               ("Weak version", "Proven (Helfgott, 2013)")],
        importance=[
            "It is one of the oldest and best-known unsolved problems in all of mathematics. It is a pure test of how primes interact with <em>addition</em>. Primes are defined by multiplication, so questions mixing them with addition tend to be very hard.",
            "The attempts have produced lasting tools: the Hardy–Littlewood <strong>circle method</strong>, Vinogradov's estimates for exponential sums, and much of modern sieve theory.",
        ],
        status=[
            "Open. The <strong>weak</strong> (ternary) Goldbach conjecture says every odd number greater than 5 is a sum of three primes. Harald Helfgott proved it completely in 2013.",
            "For the original (binary) version, we know that <em>almost all</em> even numbers are sums of two primes: any exceptions are extremely rare. We also know every large enough even number is a prime plus a number with at most two prime factors (Chen).",
            "The number of ways to write 2<em>n</em> as a sum of two primes appears to grow steadily with <em>n</em>. A plot of these counts, called the \"Goldbach comet\", makes it very believable that the count never drops to zero.",
        ],
        timeline=[
            ("1742", "Christian Goldbach writes to Euler proposing the conjecture."),
            ("1923", "Hardy and Littlewood develop the circle method and give a conditional attack on the ternary problem."),
            ("1930", "Schnirelmann proves every integer greater than 1 is a sum of at most some fixed number of primes."),
            ("1937", "Vinogradov proves the weak conjecture for all sufficiently large odd numbers."),
            ("1938", "Chudakov, van der Corput and Estermann show almost all even numbers are sums of two primes."),
            ("1973", "Chen: every large even number is prime + (prime or semiprime)."),
            ("2013", "Helfgott completes the proof of the weak Goldbach conjecture. Oliveira e Silva, Herzog and Pardi verify the binary one up to 4 × 10¹⁸."),
        ],
        approaches=[
            "<strong>Circle method.</strong> This method counts representations by integrating an exponential sum around a circle. For three primes, the \"minor arcs\" (the messy part) can be controlled. For two primes they cannot. Any new way to bound that error term would be a breakthrough.",
            "<strong>Sieve plus parity.</strong> As with twin primes, sieves stall at \"prime plus almost-prime\" because of the parity problem. Ideas that break parity for one problem often transfer to the other.",
            "<strong>Shrink the exceptional set.</strong> Proving that the number of exceptions up to <em>x</em> is at most <em>x</em><sup>δ</sup> for ever smaller δ is steady, measurable progress.",
        ],
        try_it="For each even number from 4 to 100, count how many ways it can be written as a sum of two primes. Plot the counts. You have drawn the start of the Goldbach comet. Which numbers have unusually many representations? (Hint: look at multiples of 3 and 5.)",
    ),
    dict(
        slug="collatz", cat="number-theory", pick=True,
        title="Collatz Conjecture",
        short="Pick any positive integer. If it's even, halve it. If it's odd, triple it and add 1. Does every starting number eventually reach 1?",
        short_status='Paul Erdős said "mathematics is not yet ready for such problems."',
        statement="For every positive integer <em>n</em>, repeatedly applying <em>n</em> → <em>n</em>/2 (if even) or <em>n</em> → 3<em>n</em> + 1 (if odd) eventually reaches 1.",
        facts=[("First posed", "Lothar Collatz, 1937"),
               ("Verified up to", "more than 2⁶⁸ ≈ 3 × 10²⁰"),
               ("Best result", "Almost all orbits get almost bounded (Tao, 2019)")],
        importance=[
            "On its own, the answer has few known consequences. It matters because it shows how badly current mathematics handles systems that mix multiplication with the digits of numbers in different bases. Here that means halving (base 2) and tripling (base 3).",
            "It is also a model for a broad class of problems. Conway showed that natural generalizations of Collatz-type rules are <strong>undecidable</strong>: no algorithm can settle all of them. So any proof for the 3<em>n</em> + 1 rule must use something special about that rule.",
        ],
        status=[
            "Open. Every number up to more than 2⁶⁸ has been checked. A counterexample would have to either climb to infinity or fall into a cycle other than 4 → 2 → 1. Any such cycle is known to be astronomically long.",
            "In 2019 Terence Tao proved the strongest result so far: for <em>almost all</em> starting numbers, the orbit eventually falls below any slowly growing bound you choose. \"Almost all\" is meant in the sense of logarithmic density. This is very close to what one expects, but it does not rule out a few exceptional numbers.",
        ],
        timeline=[
            ("1937", "Lothar Collatz poses the problem."),
            ("1972", "Conway shows generalized Collatz problems can be undecidable."),
            ("1976", "Terras proves almost every number eventually drops below its starting value."),
            ("2003", "Krasikov and Lagarias: at least <em>x</em><sup>0.84</sup> of the numbers up to <em>x</em> reach 1."),
            ("2019", "Tao: almost all Collatz orbits attain almost bounded values."),
            ("2020s", "Computer verification is pushed beyond 2⁶⁸. Researchers also recast the problem as rewriting systems to be attacked with SAT solvers (Yolcu, Aaronson and Heule)."),
        ],
        approaches=[
            "<strong>Probabilistic heuristics.</strong> Each odd step followed by the halvings that come after it multiplies <em>n</em> by about 3/4 on average, so orbits should drift downward. Making this rigorous for <em>every</em> number, not just almost every number, is the core difficulty.",
            "<strong>2-adic dynamics.</strong> The map extends naturally to the 2-adic integers, where it is well understood (it is conjugate to a shift map). The challenge is to control what happens to ordinary integers inside that space.",
            "<strong>Automated reasoning.</strong> Encode the problem as termination of a string-rewriting system and search for a termination proof by computer. This has proven weaker variants, though not the full problem.",
            "<strong>Rule out cycles.</strong> Continued-fraction bounds on log₂3 already show that any other cycle must be enormous. Pushing these bounds further, alongside ruling out divergence, would cover both ways the conjecture could fail.",
        ],
        try_it="Start from 27 and follow the rule by hand or in a spreadsheet. It takes 111 steps to reach 1 and climbs as high as 9,232 along the way. Then try 26 or 28 for contrast.",
    ),
    dict(
        slug="odd-perfect-numbers", cat="number-theory", pick=False,
        title="Odd Perfect Numbers",
        short="A perfect number equals the sum of its proper divisors: 6 = 1 + 2 + 3, and 28 = 1 + 2 + 4 + 7 + 14. Every known perfect number is even. Does an odd one exist?",
        short_status=None,
        statement="There is no odd number <em>n</em> whose divisors (including <em>n</em>) add up to 2<em>n</em>.",
        facts=[("First studied", "Euclid, c. 300 BC"),
               ("Known perfect numbers", "52, all even"),
               ("An odd one would be", "greater than 10¹⁵⁰⁰")],
        importance=[
            "It may be the oldest unsolved problem in mathematics, going back to the ancient Greeks.",
            "Even perfect numbers are completely understood. By Euclid and Euler, they are exactly the numbers 2<sup><em>p</em>−1</sup>(2<sup><em>p</em></sup> − 1) where 2<sup><em>p</em></sup> − 1 is a Mersenne prime. The odd case resists every approach, so it is a benchmark for how well we understand the divisor-sum function.",
        ],
        status=[
            "Open, but an odd perfect number is squeezed by a long list of constraints. Among them:",
            "<ul><li>It must exceed 10¹⁵⁰⁰ (Ochem and Rao, 2012).</li><li>It must have at least 10 distinct prime factors (Nielsen, 2015).</li><li>It must have the form <em>p</em><sup>α</sup><em>m</em>² with <em>p</em> ≡ α ≡ 1 (mod 4), a fact already known to Euler.</li><li>Its largest prime factor must exceed 10⁸.</li></ul>",
            "A heuristic argument of Pomerance suggests none exist, but no proof is in sight.",
        ],
        timeline=[
            ("c. 300 BC", "Euclid shows 2<sup><em>p</em>−1</sup>(2<sup><em>p</em></sup> − 1) is perfect when 2<sup><em>p</em></sup> − 1 is prime."),
            ("1638", "Descartes finds the \"spoof\" 198585576189 = 3²·7²·11²·13²·22021. It would be an odd perfect number if 22021 were prime (it is 19²·61)."),
            ("1747", "Euler proves every even perfect number has Euclid's form, and shows an odd one must have the form <em>p</em><sup>α</sup><em>m</em>²."),
            ("1913", "Dickson proves there are only finitely many odd perfect numbers with a given number of prime factors."),
            ("2012", "Ochem and Rao push the lower bound past 10¹⁵⁰⁰."),
            ("2015", "Nielsen shows at least 10 distinct prime factors are needed."),
            ("2024", "The 52nd Mersenne prime, 2<sup>136279841</sup> − 1, gives the 52nd known (even) perfect number."),
        ],
        approaches=[
            "<strong>Tighten the constraints until they conflict.</strong> Most progress comes from adding more necessary conditions and hoping they eventually contradict each other. Computer searches over factorization trees are central to this.",
            "<strong>Study spoofs.</strong> Recent work (for example, the Brigham Young University group) looks at \"spoof\" perfect numbers like Descartes's, where some factor is treated as if it were prime. Understanding why spoofs exist while real odd perfect numbers (apparently) don't may show where a proof has to bite.",
            "<strong>Density arguments.</strong> Proving that odd perfect numbers up to <em>x</em> number fewer than any power of <em>x</em> is known. Upgrading this to zero needs a genuinely new idea.",
        ],
        try_it="Check that 496 and 8128 are perfect. Then take an odd number with lots of divisors, like 945 = 3³·5·7. Its divisors sum to more than 2 × 945 (it is \"abundant\"). Odd abundant numbers exist, so why can't one land exactly on 2<em>n</em>?",
    ),
    dict(
        slug="riemann-hypothesis", cat="number-theory", pick=False,
        title="Riemann Hypothesis",
        short="A claim about where the zeros of a certain function lie. Put simply, it says the primes are spread out as evenly as they can be.",
        short_status="A Millennium Prize problem worth $1M. Hundreds of other results assume it is true.",
        statement="Every non-trivial zero of the Riemann zeta function ζ(<em>s</em>) = 1 + 2<sup>−<em>s</em></sup> + 3<sup>−<em>s</em></sup> + ⋯ has real part exactly 1/2.",
        facts=[("First posed", "Bernhard Riemann, 1859"),
               ("Prize", "$1,000,000 (Clay Millennium Problem)"),
               ("Zeros checked", "more than 10¹³, all on the line")],
        importance=[
            "Riemann found an exact formula linking the primes to the zeros of ζ. Each zero contributes a \"wave\" to the count of primes. The hypothesis is equivalent to saying the number of primes up to <em>x</em> differs from the smooth estimate Li(<em>x</em>) by at most about √<em>x</em> · ln <em>x</em>. That is the smallest error one could hope for, so the primes would be as regular as possible.",
            "Hundreds of theorems are proved \"assuming RH\" or its generalizations. One example: under the generalized RH, the Miller primality test is deterministic and fast. A proof would upgrade all of them at once.",
            "It sits at a crossroads of number theory, analysis, random matrix theory and even quantum physics.",
        ],
        status=[
            "Open. Numerically, more than ten trillion zeros have been checked and all lie on the critical line. Theoretically, we know a positive proportion of zeros lie on the line: currently over 41%.",
            "The analogue of RH for curves and varieties over finite fields is <em>proven</em>, by Weil and later Deligne, and it is one of the triumphs of 20th-century mathematics. Many hope a similar structure can be found for the integers.",
        ],
        timeline=[
            ("1859", "Riemann's only paper on number theory states the hypothesis."),
            ("1896", "Hadamard and de la Vallée Poussin prove the prime number theorem by showing no zeros lie on the line Re(<em>s</em>) = 1."),
            ("1914", "Hardy proves infinitely many zeros lie on the critical line."),
            ("1942", "Selberg shows a positive proportion do."),
            ("1948–74", "Weil (curves) and then Deligne (general varieties) prove the finite-field analogue."),
            ("1973", "Montgomery and Dyson notice that spacings between zeros match eigenvalues of random matrices."),
            ("1989", "Conrey: at least 40% of zeros are on the line."),
            ("2018", "Rodgers and Tao prove the de Bruijn–Newman constant Λ ≥ 0. Since RH is equivalent to Λ ≤ 0, RH is true \"only barely\", if at all."),
            ("2024", "Guth and Maynard improve Ingham's 1940 bound on zeros away from the line, the first major advance there in 80 years."),
        ],
        approaches=[
            "<strong>Hilbert–Pólya.</strong> Find a natural self-adjoint operator whose eigenvalues are the zeros. Self-adjointness would force them onto the line. The random-matrix statistics strongly suggest such an operator exists.",
            "<strong>Copy the finite-field proof.</strong> Deligne's proof uses cohomology and a Frobenius action. The dream is a \"field with one element\" or some other geometry in which the integers behave like a curve.",
            "<strong>Zero-density and moment estimates.</strong> Incremental progress, such as Guth–Maynard, shows fewer zeros can stray from the line. This doesn't prove RH, but it gives many of its consequences unconditionally.",
            "<strong>Positivity criteria.</strong> RH is equivalent to many positivity statements, for example Li's criterion and Weil's explicit formula. Proving one of them directly is another route.",
        ],
        try_it="Compare π(<em>x</em>), the number of primes up to <em>x</em>, with Li(<em>x</em>) for <em>x</em> = 1,000, 10,000 and 100,000 using any online calculator. See how small the difference is compared with √<em>x</em>.",
    ),
    dict(
        slug="legendre", cat="number-theory", pick=False,
        title="Legendre's Conjecture",
        short="Is there always a prime between n² and (n+1)²?",
        short_status=None,
        statement="For every positive integer <em>n</em>, there is a prime between <em>n</em>² and (<em>n</em> + 1)².",
        facts=[("First posed", "Adrien-Marie Legendre, c. 1800"),
               ("Landau's problems", "One of Landau's four (1912)"),
               ("Best known", "Primes in [<em>x</em>, <em>x</em> + <em>x</em><sup>0.525</sup>]")],
        importance=[
            "It is a statement about <strong>primes in short intervals</strong>. The interval from <em>n</em>² to (<em>n</em>+1)² has length about 2√<em>x</em> when <em>x</em> = <em>n</em>². So the conjecture says that gaps between primes are always shorter than about 2√<em>x</em>.",
            "Remarkably, even the Riemann Hypothesis doesn't imply it: RH gives gaps of size √<em>x</em> · ln <em>x</em>, which is just barely too weak. That makes it a good measure of how far beyond RH our understanding of primes has to go.",
        ],
        status=[
            "Open. The best unconditional result guarantees a prime in every interval [<em>x</em>, <em>x</em> + <em>x</em><sup>0.525</sup>] for large <em>x</em> (Baker, Harman and Pintz, 2001). Legendre needs exponent 1/2.",
            "Ingham proved the cubic analogue in 1937: there is always a prime between <em>n</em>³ and (<em>n</em>+1)³ for large <em>n</em>. Later work made \"large\" explicit.",
        ],
        timeline=[
            ("1845–52", "Bertrand conjectures, and Chebyshev proves, that there is always a prime between <em>n</em> and 2<em>n</em>."),
            ("1912", "Landau lists it among four \"unattackable\" problems about primes (the other three: Goldbach, twin primes, and primes of the form <em>n</em>² + 1)."),
            ("1936", "Cramér conjectures prime gaps are at most about (ln <em>x</em>)². This would imply Legendre easily."),
            ("1937", "Ingham: primes between consecutive cubes (for large <em>n</em>)."),
            ("2001", "Baker, Harman and Pintz: a prime in [<em>x</em>, <em>x</em> + <em>x</em><sup>0.525</sup>]."),
        ],
        approaches=[
            "<strong>Lower the exponent.</strong> Each improvement from 0.525 toward 0.5 comes from sharper zero-density estimates and sieve refinements. The recent Guth–Maynard zero-density bound improves results about primes in short intervals \"on average\".",
            "<strong>Go beyond RH.</strong> Since RH alone is insufficient, a proof needs additional input, such as the pair-correlation conjecture or good control of zeros near the critical line.",
            "<strong>Averaged versions.</strong> Proving it holds for almost all <em>n</em> is already within reach of current methods. Upgrading \"almost all\" to \"all\" is the hard part.",
        ],
        try_it="For <em>n</em> = 1 to 30, count the primes between <em>n</em>² and (<em>n</em>+1)². The minimum count stays at 1 or 2 for small <em>n</em> but trends upward. Does it look like it could ever hit 0?",
    ),
    # ------------------------------------------------------------------ CS and logic
    dict(
        slug="p-vs-np", cat="cs-logic", pick=False,
        title="P vs NP",
        short="If a solution is quick to <em>check</em>, is it also quick to <em>find</em>? Sudoku is an example: checking a filled grid is easy, but solving one seems hard.",
        short_status="Most online security assumes P ≠ NP. Also a $1M Millennium Prize problem.",
        statement="Is every problem whose solutions can be verified in polynomial time (NP) also solvable in polynomial time (P)? Most researchers believe P ≠ NP.",
        facts=[("Formalized", "Cook (1971) and Levin (1973)"),
               ("Prize", "$1,000,000 (Clay Millennium Problem)"),
               ("NP-complete problems", "Thousands known")],
        importance=[
            "If P = NP with a practical algorithm, most public-key cryptography would break. Many hard optimization problems in logistics, chip design and biology would become easy. Even <em>finding mathematical proofs</em> would become roughly as easy as checking them.",
            "If P ≠ NP, as expected, it would confirm that creativity and search are fundamentally harder than verification. It would also put the foundations of cryptography on firm ground.",
            "Thousands of natural problems are NP-complete: Sudoku, scheduling, the traveling salesperson problem, protein folding models, Tetris and more. A fast algorithm for any one of them would solve all of them.",
        ],
        status=[
            "Open, and widely considered one of the hardest problems in mathematics. Three proven \"barriers\" show that whole families of proof techniques cannot resolve it on their own: relativization, natural proofs and algebrization.",
            "Researchers <em>can</em> prove strong lower bounds for restricted models of computation, such as constant-depth circuits and monotone circuits. Extending these to general circuits is the central challenge.",
        ],
        timeline=[
            ("1956", "Gödel asks von Neumann, in a letter, essentially this question."),
            ("1971", "Cook proves that satisfiability (SAT) is NP-complete. Levin finds the same result independently in the USSR."),
            ("1972", "Karp shows 21 classic problems are NP-complete."),
            ("1975", "Baker, Gill and Solovay: the relativization barrier."),
            ("1981–87", "Furst–Saxe–Sipser, Ajtai, Håstad: parity cannot be computed by small constant-depth circuits. Razborov proves exponential lower bounds for monotone circuits."),
            ("1994", "Razborov and Rudich: the natural proofs barrier."),
            ("2008", "Aaronson and Wigderson: the algebrization barrier."),
            ("2011", "Ryan Williams proves NEXP ⊄ ACC⁰ by turning faster algorithms into lower bounds."),
        ],
        approaches=[
            "<strong>Circuit lower bounds.</strong> Show that some NP problem requires super-polynomial circuit size. Progress here has been slow but real.",
            "<strong>Algorithms to lower bounds.</strong> Williams's program shows that even slightly faster-than-brute-force algorithms for circuit problems imply new lower bounds. It is one of the few approaches known to get around the barriers.",
            "<strong>Geometric Complexity Theory.</strong> Mulmuley and Sohoni use algebraic geometry and representation theory to separate algebraic analogues of P and NP (permanent vs determinant).",
            "<strong>Proof complexity.</strong> Show that certain proof systems need super-polynomially long proofs of some tautologies. Doing this for every proof system would prove NP ≠ coNP, and hence P ≠ NP.",
        ],
        try_it="Solve a hard Sudoku and time yourself. Then have a friend check your solution and time them. The gap between those two times is the intuition behind P vs NP.",
    ),
    # ------------------------------------------------------------------ geometry and combinatorics
    dict(
        slug="inscribed-square", cat="geometry", pick=True,
        title="Inscribed Square Problem (Toeplitz)",
        short="Does every closed loop drawn without crossing itself contain four points that form a square?",
        short_status="Proven for smooth curves, still open for arbitrary continuous ones.",
        statement="Every Jordan curve (a continuous closed loop in the plane that does not cross itself) contains four points that are the corners of a square.",
        facts=[("First posed", "Otto Toeplitz, 1911"),
               ("Proven for", "Convex, smooth and many other curves"),
               ("Rectangles", "Every Jordan curve inscribes one")],
        importance=[
            "It is one of the simplest open questions in geometry: a child can understand it. Yet it touches deep topology, because \"continuous curve\" includes wildly wiggly, fractal-like loops.",
            "Recent progress used <strong>symplectic geometry</strong>, a field born from physics. So this elementary problem has become a showcase for powerful modern tools.",
        ],
        status=[
            "Open for general continuous curves. It is proven for convex curves, piecewise-analytic curves, smooth curves, locally monotone curves and several other large classes.",
            "The difficulty is a limit problem. Approximate a wild curve by smooth ones, each of which contains a square. Those squares might shrink to a single point in the limit, and a point is not a square.",
            "In 2020 Greene and Lobb proved that every <em>smooth</em> Jordan curve contains a rectangle of <em>every</em> aspect ratio, not just squares. The proof uses Lagrangian tori in four-dimensional space.",
        ],
        timeline=[
            ("1911", "Toeplitz announces the problem."),
            ("1913", "Emch proves it for convex curves."),
            ("1929", "Schnirelmann proves it for sufficiently smooth curves."),
            ("1977", "Vaughan gives a beautiful proof, using a Möbius strip, that every Jordan curve contains a <em>rectangle</em>."),
            ("1989", "Stromquist proves it for \"locally monotone\" curves, a large class."),
            ("2017", "Tao proves it for curves formed by two Lipschitz graphs with constant less than 1."),
            ("2020", "Greene and Lobb: smooth curves contain rectangles of every aspect ratio."),
        ],
        approaches=[
            "<strong>Control the size of the square.</strong> Show that for any curve enclosing a region of a given area, some inscribed square has size bounded below. Then limits of approximations can't collapse.",
            "<strong>Symplectic topology.</strong> Extend Greene and Lobb's Lagrangian methods from smooth curves to rougher ones.",
            "<strong>Parity and counting.</strong> For generic smooth curves, the number of inscribed squares is odd. Find a version of that invariant that survives for continuous curves.",
        ],
        try_it="Draw a random closed loop on paper, the stranger the better, and try to find a square with its four corners on the loop. Rotating a transparent square template helps. It seems always possible, which is why the problem is so tantalizing.",
    ),
    dict(
        slug="moving-sofa", cat="geometry", pick=False,
        title="Moving Sofa Problem",
        short="What is the largest shape you can carry around a right-angled corner in a hallway 1 unit wide?",
        short_status="Baek claimed a solution in 2024, and it is still being verified.",
        statement="Find the rigid planar shape of largest area that can be moved around a right-angled corner in a hallway of width 1.",
        facts=[("First posed", "Leo Moser, 1966"),
               ("Best known sofa", "Gerver's, area ≈ 2.2195"),
               ("Claimed proof", "Jineon Baek, 2024")],
        importance=[
            "It is a clean example of <strong>shape optimization</strong>, where the unknown is an entire shape rather than a number. Problems like this are notoriously hard because the space of possible shapes is infinite-dimensional.",
            "It has become a test case for combining geometric insight with computer-assisted proofs.",
        ],
        status=[
            "Possibly solved. In 2024 Jineon Baek posted a proof, over 100 pages long, that Gerver's sofa is optimal. Experts are still checking it. Before that, the best upper bound was about 2.37 (Kallus and Romik, 2018).",
            "Gerver's sofa is bounded by 18 distinct curve pieces. The claimed answer, about 2.2195, has no known simple closed form.",
        ],
        timeline=[
            ("1966", "Leo Moser poses the problem."),
            ("1968", "Hammersley finds a telephone-shaped sofa of area π/2 + 2/π ≈ 2.2074, and proves no sofa can exceed 2√2 ≈ 2.83."),
            ("1992", "Gerver finds a slightly better sofa (≈ 2.2195) and conjectures it is optimal."),
            ("2018", "Kallus and Romik use computer-assisted proofs to show no sofa exceeds 2.37. Romik also finds exact formulas for Gerver's sofa and solves an \"ambidextrous\" variant."),
            ("2024", "Baek claims a full proof that Gerver's sofa is optimal."),
        ],
        approaches=[
            "<strong>Verify Baek's proof.</strong> The most important current task is careful checking and, ideally, simplification.",
            "<strong>Convex relaxation.</strong> Baek's approach reformulates the problem so that an upper bound becomes a concave optimization, which can be solved exactly. Finding simpler relaxations could give a shorter proof.",
            "<strong>Variants.</strong> Other corridor angles, three-dimensional versions and ambidextrous sofas are open and may be more approachable.",
        ],
        try_it="Cut shapes out of paper and push them around an L-shaped corridor drawn with 1-unit width (say 5 cm). A semicircle of radius 1 (area ≈ 1.57) works. Can you beat Hammersley's 2.2074 by hand?",
    ),
    dict(
        slug="hadwiger-nelson", cat="geometry", pick=False,
        title="Hadwiger–Nelson Problem",
        short="What is the fewest colors needed to color every point of the plane so that no two points exactly 1 unit apart share a color?",
        short_status="The answer is known to be 5, 6 or 7.",
        statement="Determine the chromatic number of the plane: the least number of colors such that no two points at distance exactly 1 receive the same color.",
        facts=[("First posed", "Edward Nelson, 1950"),
               ("Lower bound", "5 (de Grey, 2018)"),
               ("Upper bound", "7 (hexagon tiling)")],
        importance=[
            "It connects geometry, graph coloring and even the foundations of mathematics. Shelah and Soifer showed that for related problems, the answer can depend on which axioms of set theory you accept, such as the axiom of choice.",
            "The 2018 lower bound was found by an amateur mathematician, Aubrey de Grey, with computer help. That makes it a striking example of how outsiders and computation can move a famous problem.",
        ],
        status=[
            "The answer is 5, 6 or 7.",
            "<ul><li><strong>7 colors suffice:</strong> tile the plane with hexagons of diameter slightly less than 1 and color them in a repeating 7-color pattern.</li><li><strong>At least 4 are needed:</strong> the Moser spindle, a graph with 7 points, cannot be 3-colored.</li><li><strong>At least 5 are needed:</strong> de Grey found a unit-distance graph with 1,581 vertices that cannot be 4-colored. The Polymath16 project later shrank it to about 500 vertices.</li></ul>",
            "If the color classes must be measurable sets, at least 5 colors were known to be needed since Falconer (1981).",
        ],
        timeline=[
            ("1950", "Nelson poses the problem. Isbell observes the 7-color hexagon tiling."),
            ("1961", "Leo and William Moser find the Moser spindle, giving a lower bound of 4."),
            ("1981", "Falconer: measurable colorings need at least 5 colors."),
            ("2003", "Shelah and Soifer show that related answers can depend on the axiom of choice."),
            ("2018", "Aubrey de Grey proves at least 5 colors are needed. Polymath16 simplifies the construction."),
        ],
        approaches=[
            "<strong>Find a 6-chromatic unit-distance graph.</strong> Use SAT solvers and clever constructions to raise the lower bound to 6.",
            "<strong>Find a 6-coloring.</strong> No known tiling uses 6 colors, and many natural candidates provably fail. A new periodic or aperiodic pattern would lower the upper bound.",
            "<strong>Restricted versions.</strong> Settle the problem for colorings whose color classes are nice shapes (for example, polygons with boundaries). This is the likeliest route to the true answer.",
        ],
        try_it="Draw the Moser spindle: two rhombi, each made of two equilateral triangles with side 1, sharing one vertex and rotated so that their far tips are exactly 1 apart. Try to 3-color its 7 points so that no unit edge joins two points of the same color. It can't be done.",
    ),
    dict(
        slug="union-closed-sets", cat="geometry", pick=False,
        title="Union-Closed Sets Conjecture (Frankl)",
        short="Take a family of sets where the union of any two sets in the family is also in it. Is some element contained in at least half of the sets?",
        short_status="Gilmer made major progress in 2022, but the full claim is still open.",
        statement="If a finite family of sets (not just the empty set) is closed under unions, then some element belongs to at least half of the sets in the family.",
        facts=[("First posed", "Péter Frankl, 1979"),
               ("Best known fraction", "just above 38.2%"),
               ("Target", "50%")],
        importance=[
            "It is one of the most famous \"simple\" problems in extremal combinatorics. It is also equivalent to natural statements about lattices and about graphs.",
            "The 2022 breakthrough is a textbook example of an idea from another field, <strong>information theory</strong> (entropy), suddenly unlocking a decades-old problem.",
        ],
        status=[
            "Open. Before 2022, nobody could even show that some element lies in a <em>fixed positive fraction</em> of the sets.",
            "In late 2022, Justin Gilmer (then at Google) proved a fraction of 1%. Within days, several groups improved it to (3 − √5)/2 ≈ 38.2%: Alweiss–Huang–Sellke, Chase–Lovett, Sawin, and others. That number is a natural limit of the entropy method, and only tiny improvements beyond it are known.",
            "The conjecture is verified for families on small ground sets and for many special classes.",
        ],
        timeline=[
            ("1979", "Frankl formulates the conjecture."),
            ("1990s–2010s", "Many special cases are proven: small ground sets, families with few sets, lattice formulations and graph versions."),
            ("2022", "Gilmer's entropy argument gives the first constant fraction (1%)."),
            ("2022", "Several groups sharpen it to ≈ 38.2% within weeks, with small improvements beyond."),
        ],
        approaches=[
            "<strong>Refine the entropy method.</strong> Gilmer compares two random sets from the family and bounds the entropy of their union. Pushing past 38.2% seems to need new coupling or correlation ideas.",
            "<strong>Structural reductions.</strong> Show that a minimal counterexample must have special structure, then rule that structure out.",
            "<strong>Lattice and graph versions.</strong> The equivalent graph formulation (about maximal stable sets in bipartite graphs) may be easier to attack with graph-theoretic tools.",
        ],
        try_it="Take the family {∅, {1}, {2,3}, {1,2,3}} and check that it is closed under unions. Count how many sets contain each element. Now try to build a union-closed family where every element appears in <em>fewer</em> than half the sets. Why does it always fail?",
    ),
    dict(
        slug="lonely-runner", cat="geometry", pick=False,
        title="Lonely Runner Conjecture",
        short="n runners start together on a circular track of length 1, each at a different constant speed. Does every runner at some moment end up at least 1/n of a lap away from all the others?",
        short_status=None,
        statement="If <em>n</em> runners start together on a circular track of length 1 and run forever at distinct constant speeds, then each runner is at some time at distance at least 1/<em>n</em> from every other runner.",
        facts=[("First posed", "Wills (1967), Cusick (1973)"),
               ("Proven for", "up to 7 runners (2008)"),
               ("Bound 1/n is", "sharp (speeds 1, 2, …, n)")],
        importance=[
            "It is a problem in <strong>Diophantine approximation</strong>: how well can multiples of several real numbers avoid the integers at the same time?",
            "It has many equivalent forms. Cusick came to it through \"view obstruction\" (seeing out of a forest of cubes). It is also connected to flows in graphs and to coloring certain distance graphs.",
        ],
        status=[
            "Open in general. Proven for up to 7 runners (Barajas and Serra, 2008). Recent computer-assisted work has been reported to push this further.",
            "Tao showed in 2018 that, to check the conjecture for a given number of runners, it is enough to check speeds below some explicit bound. So each fixed case is in principle a finite computation, though the bound is enormous.",
            "The bound 1/<em>n</em> cannot be improved: with speeds 0, 1, 2, …, <em>n</em>−1, the runner at speed 0 is never farther than 1/<em>n</em> from everyone.",
        ],
        timeline=[
            ("1967", "Wills poses the problem in the language of Diophantine approximation."),
            ("1973", "Cusick independently arrives at it through view obstruction."),
            ("1998", "Bienia et al. give the \"lonely runner\" name and link it to nowhere-zero flows."),
            ("2001", "Bohman, Holzman and Kleitman prove it for 6 runners (with a simpler proof by Renault in 2004)."),
            ("2008", "Barajas and Serra prove it for 7 runners."),
            ("2018", "Tao reduces each case to finitely many speed sets."),
        ],
        approaches=[
            "<strong>Finite checks plus computers.</strong> Shrink Tao's speed bound until each next case can be checked by computer.",
            "<strong>Zonotope geometry.</strong> Henze and Malikiosis reformulated it in terms of covering radii of zonotopes (sums of line segments). This brings in tools from convex geometry.",
            "<strong>Relaxations.</strong> Prove the conjecture with a slightly weaker distance, say 1/(2<em>n</em>), and then tighten. Also consider \"almost all speeds\" versions, which are known.",
        ],
        try_it="Simulate 3 runners with speeds 1, 2 and 3 on a track of length 1 in a spreadsheet. Record each runner's distance to the nearest other runner at time steps of 0.01. Does each one ever get 1/3 of a lap away from both others?",
    ),
    # ------------------------------------------------------------------ numbers themselves
    dict(
        slug="pi-plus-e", cat="numbers", pick=False,
        title="Is π + e irrational?",
        short="We know π and e are each irrational, but not whether their sum or product is.",
        short_status="The same question is open for the Euler–Mascheroni constant γ.",
        statement="Is π + <em>e</em> irrational? Is π<em>e</em>? Is Euler's constant γ = lim (1 + 1/2 + ⋯ + 1/<em>n</em> − ln <em>n</em>) ≈ 0.5772 irrational?",
        facts=[("π transcendental", "Lindemann, 1882"),
               ("e transcendental", "Hermite, 1873"),
               ("Known", "At least one of π + e and πe is transcendental")],
        importance=[
            "These questions show how little we can prove about specific numbers. Almost every real number is transcendental, yet proving it for any <em>particular</em> number is extremely hard.",
            "They test <strong>transcendence theory</strong> directly. A central conjecture there, Schanuel's conjecture, would settle π + <em>e</em> and thousands of similar questions at once.",
        ],
        status=[
            "Open. One easy fact: π + <em>e</em> and π<em>e</em> can't both be rational, or even both algebraic. If they were, π and <em>e</em> would be roots of <em>x</em>² − (π+<em>e</em>)<em>x</em> + π<em>e</em>, making them algebraic, which they are not. But we don't know which of the two is transcendental.",
            "For γ, not even irrationality is known. If γ were a fraction, its denominator would need hundreds of thousands of digits.",
            "Some related results <em>are</em> known. <em>e</em><sup>π</sup> is transcendental (Gelfond–Schneider). π and <em>e</em><sup>π</sup> are algebraically independent (Nesterenko, 1996). ζ(3) is irrational (Apéry, 1978).",
        ],
        timeline=[
            ("1737", "Euler proves <em>e</em> is irrational."),
            ("1761", "Lambert proves π is irrational."),
            ("1873–82", "Hermite (<em>e</em>) and Lindemann (π) prove transcendence."),
            ("1934", "Gelfond and Schneider: <em>a</em><sup><em>b</em></sup> is transcendental for algebraic <em>a</em> ≠ 0, 1 and irrational algebraic <em>b</em>. This gives <em>e</em><sup>π</sup> = (−1)<sup>−i</sup>."),
            ("1960s", "Schanuel formulates his conjecture."),
            ("1978", "Apéry shocks the community by proving ζ(3) is irrational."),
            ("1996", "Nesterenko proves π, <em>e</em><sup>π</sup> and Γ(1/4) are algebraically independent."),
        ],
        approaches=[
            "<strong>Schanuel's conjecture.</strong> It implies that π and <em>e</em> are algebraically independent, which settles the question immediately. Proving it would be a revolution.",
            "<strong>Apéry-style approximations.</strong> Find a sequence of fractions converging to γ (or π + <em>e</em>) so fast that the number can't be rational. This is how irrationality of ζ(3) was proven.",
            "<strong>Periods.</strong> Kontsevich and Zagier define \"periods\" (integrals of algebraic functions). π is a period, and <em>e</em> and γ are conjectured not to be. Understanding periods may clarify which relations can hold.",
        ],
        try_it="Compute π + <em>e</em> ≈ 5.859874482… to many digits and find its continued fraction expansion (many calculators and websites do this). Rational numbers have finite continued fractions. Does yours look like it will stop?",
    ),
    # ------------------------------------------------------------------ graph theory
    dict(
        slug="ramsey-r55", cat="graph-theory", pick=True,
        title="Ramsey number R(5,5)",
        short="How many people must be at a party to guarantee that 5 of them all know each other, or 5 of them are all strangers? For groups of 3 the answer is 6, and for groups of 4 it is 18.",
        short_status="For groups of 5 it is only known to be between 43 and 46. Erdős joked that if aliens demanded this number, we should put every computer on Earth to work on it. If they asked for R(6,6), we should attack them instead.",
        statement="Find the smallest <em>N</em> such that every red/blue coloring of the edges of the complete graph on <em>N</em> vertices contains 5 vertices whose connecting edges are all the same color.",
        facts=[("Known range", "43 ≤ R(5,5) ≤ 46"),
               ("R(3,3), R(4,4)", "6 and 18"),
               ("Conjectured value", "43")],
        importance=[
            "Ramsey theory is the mathematics of \"complete disorder is impossible\": any large enough structure contains an orderly piece. R(5,5) is the smallest diagonal case we can't compute, so it is a benchmark for both theory and computation.",
            "Erdős's 1947 lower bound for Ramsey numbers launched the <strong>probabilistic method</strong>, now one of the most important tools in combinatorics and computer science.",
        ],
        status=[
            "Open. Exoo (1989) found a coloring on 42 vertices with no single-colored group of 5, so R(5,5) ≥ 43. In 2024, Angeltveit and McKay used massive computation to show R(5,5) ≤ 46. The widely believed answer is 43.",
            "For large <em>k</em>, R(<em>k</em>,<em>k</em>) lies between roughly √2<sup><em>k</em></sup> and 4<sup><em>k</em></sup>. In 2023, Campos, Griffiths, Morris and Sahasrabudhe made the first exponential improvement to the upper bound in about 90 years, to below 3.993<sup><em>k</em></sup>.",
        ],
        timeline=[
            ("1930", "Frank Ramsey proves that Ramsey numbers exist."),
            ("1935", "Erdős and Szekeres give the upper bound of about 4<sup><em>k</em></sup>."),
            ("1947", "Erdős proves the lower bound √2<sup><em>k</em></sup> by showing a random coloring works. This is the birth of the probabilistic method."),
            ("1955", "Greenwood and Gleason: R(3,3) = 6 and R(4,4) = 18."),
            ("1989", "Exoo: R(5,5) ≥ 43."),
            ("1995–2018", "Upper bound lowered step by step: 49, then 48."),
            ("2023", "Campos–Griffiths–Morris–Sahasrabudhe: exponential improvement for R(<em>k</em>,<em>k</em>)."),
            ("2024", "Angeltveit and McKay: R(5,5) ≤ 46."),
        ],
        approaches=[
            "<strong>Smarter exhaustive search.</strong> Use symmetry reduction, SAT solvers and linear programming to rule out 2-colorings of 45, 44 and eventually 43 vertices.",
            "<strong>Flag algebras.</strong> Razborov's semidefinite-programming method gives computer-verified upper bounds for small Ramsey-type numbers.",
            "<strong>Better constructions.</strong> A 43-vertex coloring with no monochromatic 5-clique would disprove the conjecture that the answer is 43. Searches so far have found none.",
        ],
        try_it="Prove R(3,3) = 6. Take 6 people. Person A knows at least 3 of the others, or is a stranger to at least 3. Say A knows 3 people. If any two of them know each other, those two plus A are 3 mutual acquaintances. If not, those 3 are mutual strangers. Then find a 5-person coloring (hint: a pentagon and a pentagram) that avoids both patterns.",
    ),
    dict(
        slug="reconstruction", cat="graph-theory", pick=True,
        title="Reconstruction Conjecture (Kelly–Ulam)",
        short='Suppose you are given every copy of a graph with one vertex deleted, as an unlabeled "deck of cards." Can you always rebuild the original graph, as long as it has at least 3 vertices?',
        short_status="Confirmed by computer for all graphs with up to 13 vertices.",
        statement="Every graph with at least 3 vertices is determined, up to isomorphism, by its <em>deck</em>: the multiset of unlabeled graphs obtained by deleting each vertex in turn.",
        facts=[("First posed", "Kelly and Ulam, 1941–42"),
               ("Verified", "All graphs up to 13 vertices"),
               ("Almost all graphs", "Reconstructible from 3 cards")],
        importance=[
            "It asks how much global information is stored in local pieces. That is a central theme across mathematics and computer science.",
            "Similar questions arise elsewhere: reconstructing molecules from fragments in chemistry, DNA from reads in biology, and structures from partial views in data science.",
        ],
        status=[
            "Open. Proven for many classes: trees, disconnected graphs, regular graphs, and maximal planar graphs. Bollobás showed that almost every graph is determined by just 3 of its cards.",
            "The conjecture <em>fails</em> for directed graphs (Stockmeyer's infinite families), for hypergraphs and for infinite graphs. So any proof must use something special about finite undirected graphs.",
            "A related <strong>edge</strong> reconstruction conjecture (using edge-deleted cards) is proven for graphs with many edges relative to the number of vertices (Lovász, Müller).",
        ],
        timeline=[
            ("1941", "Kelly and Ulam formulate the conjecture."),
            ("1957", "Kelly proves it for trees. \"Kelly's lemma\": the deck determines how many copies of each smaller subgraph the graph contains."),
            ("1972–77", "Lovász and Müller prove edge reconstruction for dense graphs."),
            ("1977", "Stockmeyer shows reconstruction fails for directed graphs."),
            ("1990", "Bollobás: almost every graph is reconstructible from 3 cards."),
            ("1997", "McKay verifies all graphs up to 11 vertices, later extended to 13."),
        ],
        approaches=[
            "<strong>Counting (Kelly's lemma).</strong> Extract ever more invariants from the deck, such as the degree sequence, spectrum, subgraph counts and the characteristic polynomial. The hope is to eventually pin down the whole graph.",
            "<strong>Minimal counterexamples.</strong> Show a smallest counterexample must be highly structured (for example, nearly regular with few automorphisms) and then rule those out.",
            "<strong>Algebraic and spectral methods.</strong> Recent work studies which spectral data the deck determines and uses it for special classes.",
        ],
        try_it="Draw a 4-vertex path and a star with 3 leaves. Write out the deck of each (4 cards, each a 3-vertex graph). Can you tell them apart from the decks alone? Then try to find two different graphs with the same deck. (Only the 2-vertex graphs work, which is why the conjecture needs 3 or more vertices.)",
    ),
    dict(
        slug="graceful-tree", cat="graph-theory", pick=True,
        title="Graceful Tree Conjecture",
        short="A tree is a connected graph with no loops. Take any tree with n vertices. Can you label its vertices 0, 1, …, n−1 so that the edge differences |a − b| are exactly 1, 2, …, n−1, each used once?",
        short_status="Checked by computer for every small tree, and a related conjecture by Ringel was proven in 2020. The general case is still open.",
        statement="Every tree has a <em>graceful labeling</em>: its <em>n</em> vertices can be labeled with 0, 1, …, <em>n</em>−1 so that the <em>n</em>−1 edge labels |<em>a</em> − <em>b</em>| are all distinct.",
        facts=[("First posed", "Ringel–Kotzig, via Rosa, 1960s"),
               ("Verified", "All trees up to 35 vertices"),
               ("Ringel's conjecture", "Proven for large n (2020)")],
        importance=[
            "Graceful labelings were introduced by Rosa to attack <strong>Ringel's conjecture</strong>: the complete graph on 2<em>n</em>+1 vertices can be split into 2<em>n</em>+1 copies of <em>any</em> tree with <em>n</em> edges. A graceful labeling gives such a split immediately by \"rotating\" the tree.",
            "Graph decompositions like this are used in the design of experiments, error-correcting codes and scheduling.",
        ],
        status=[
            "Open. The conjecture is proven for paths, stars, caterpillars (trees where every vertex is on or next to a central path), trees with at most 4 leaves, and many other families. It has been checked by computer for every tree with up to 35 vertices.",
            "Ringel's conjecture itself was proven for all large <em>n</em> in 2020, independently by Montgomery–Pokrovskiy–Sudakov and by Keevash–Staden. They used probabilistic \"absorption\" methods instead of graceful labelings.",
            "Montgomery and Pokrovskiy also showed that every tree has an <em>almost</em> graceful labeling, where all but a tiny fraction of edge labels are distinct.",
        ],
        timeline=[
            ("1963", "Ringel poses his decomposition conjecture."),
            ("1967", "Rosa introduces \"β-valuations\" (later called graceful labelings). The conjecture that every tree is graceful becomes known as the Ringel–Kotzig conjecture."),
            ("1970s–2000s", "Hundreds of papers prove special cases. Gallian's dynamic survey lists thousands of results on graph labelings."),
            ("2010", "Computer verification reaches all trees with up to 35 vertices."),
            ("2020", "Ringel's conjecture proven for large <em>n</em> (Montgomery–Pokrovskiy–Sudakov; Keevash–Staden)."),
        ],
        approaches=[
            "<strong>Absorption and randomness.</strong> Label most of the tree randomly, keep a flexible reserve, and use it to fix the remaining conflicts. This works approximately. Making it exact is the challenge.",
            "<strong>Transformations.</strong> Find operations that turn a graceful labeling of one tree into a graceful labeling of a modified tree, and connect every tree to a known graceful one.",
            "<strong>Structural induction.</strong> Handle trees by their diameter, number of leaves or other structure, extending the long list of proven classes.",
        ],
        try_it="Draw a star with 4 leaves and label the center 0 and the leaves 1, 2, 3, 4. That's graceful. Now draw a path with 5 vertices and try labeling it 0, 4, 1, 3, 2. Check the differences. Then pick a random tree with 7 vertices and find a graceful labeling by hand.",
    ),
    dict(
        slug="hadwiger", cat="graph-theory", pick=False,
        title="Hadwiger's Conjecture",
        short="A far-reaching generalization of the Four Color Theorem. Suppose a graph needs k colors so that neighboring vertices get different colors. Then, by deleting and contracting edges, you should be able to shrink it into k vertices that are all joined to each other.",
        short_status="Proven for k ≤ 6, open for every larger k.",
        statement="Every graph with chromatic number at least <em>k</em> contains the complete graph <em>K<sub>k</sub></em> as a minor. Equivalently, graphs with no <em>K<sub>k</sub></em> minor can be colored with <em>k</em>−1 colors.",
        facts=[("First posed", "Hugo Hadwiger, 1943"),
               ("Proven for", "k ≤ 6"),
               ("Best general bound", "O(k log log k) colors")],
        importance=[
            "Bollobás called it \"one of the deepest unsolved problems in graph theory.\" It explains <em>why</em> graphs need many colors: the only reason would be a large, tightly connected core.",
            "The case <em>k</em> = 5 is equivalent to the Four Color Theorem, so the conjecture is a vast generalization of that famous result.",
        ],
        status=[
            "Proven for <em>k</em> ≤ 6. The case <em>k</em> = 6 (Robertson, Seymour and Thomas, 1993) reduces to the Four Color Theorem. Open for every <em>k</em> ≥ 7.",
            "It is known that graphs without a <em>K<sub>k</sub></em> minor can be colored with O(<em>k</em> log log <em>k</em>) colors (Delcourt and Postle, 2021, building on Norin–Postle–Song). Proving even O(<em>k</em>), a linear bound, remains open.",
            "It holds for almost all graphs (Bollobás, Catlin and Erdős, 1980). Hajós's stronger conjecture, which asks for subdivisions instead of minors, is <em>false</em> (Catlin, 1979).",
        ],
        timeline=[
            ("1937", "Wagner shows the <em>k</em> = 5 case is equivalent to the Four Color Conjecture."),
            ("1943", "Hadwiger states the conjecture and proves it for <em>k</em> ≤ 4."),
            ("1976", "Appel and Haken prove the Four Color Theorem, settling <em>k</em> = 5."),
            ("1980", "Bollobás, Catlin and Erdős show it holds for almost all graphs."),
            ("1984", "Kostochka and Thomason prove O(<em>k</em> √log <em>k</em>) colors suffice."),
            ("1993", "Robertson, Seymour and Thomas prove <em>k</em> = 6."),
            ("2019–21", "Norin, Postle and Song, then Delcourt and Postle, break the √log barrier: O(<em>k</em> log log <em>k</em>)."),
        ],
        approaches=[
            "<strong>Linear Hadwiger.</strong> Prove that <em>Ck</em> colors suffice for some constant <em>C</em>. This is the natural next milestone.",
            "<strong>The case k = 7.</strong> Structure theory of graphs without a <em>K</em>₇ minor might settle it, but the analysis is expected to be enormous.",
            "<strong>Graph minor theory.</strong> Robertson and Seymour's structure theorem describes graphs without a given minor. Turning that description into colorings is a long-term program.",
        ],
        try_it="The complete graph <em>K</em>₄ needs 4 colors and is itself a <em>K</em>₄ minor. Now take an odd cycle of length 5 (it needs 3 colors) and find a <em>K</em>₃ minor by contracting edges. Can you find a planar graph that needs 4 colors? Its <em>K</em>₄ minor should be easy to spot.",
    ),
    dict(
        slug="erdos-gyarfas", cat="graph-theory", pick=False,
        title="Erdős–Gyárfás Conjecture",
        short="Suppose every vertex in a graph has at least 3 neighbors. Must the graph contain a cycle whose length is a power of 2 (4, 8, 16, …)?",
        short_status=None,
        statement="Every graph in which every vertex has degree at least 3 contains a cycle whose length is a power of 2.",
        facts=[("First posed", "Erdős and Gyárfás, 1995"),
               ("Smallest counterexample", "would need at least 17 vertices"),
               ("Large-degree version", "Proven (Liu–Montgomery)")],
        importance=[
            "It is about the <strong>cycle spectrum</strong>: which cycle lengths a graph must contain. Minimum degree 3 forces many cycles, and the question is whether they can all dodge the powers of 2, which get sparser as they grow.",
            "Erdős offered money for it: $100 for a proof and $50 for a counterexample. This reflects his belief that it is true but that a counterexample wouldn't be shocking.",
        ],
        status=[
            "Open. Known for several classes, including claw-free graphs and 3-connected cubic planar graphs (Heckman and Krakovski, 2013).",
            "Computer searches show any counterexample must have at least 17 vertices, and a cubic one at least 30.",
            "Liu and Montgomery proved that if the minimum (or average) degree is large enough, the graph must contain a cycle of power-of-2 length. The difficulty is the small value 3.",
        ],
        timeline=[
            ("1995", "Erdős and Gyárfás pose the conjecture."),
            ("2000s", "Proven for claw-free graphs and several other classes. Computer searches establish lower bounds on counterexamples."),
            ("2013", "Heckman and Krakovski prove it for 3-connected cubic planar graphs."),
            ("2020–23", "Liu and Montgomery prove the large-degree version with sublinear expanders."),
        ],
        approaches=[
            "<strong>Lower the degree threshold.</strong> Liu and Montgomery's expander methods need a large constant. Reducing it toward 3 would be decisive.",
            "<strong>Cubic graphs first.</strong> A minimal counterexample can be assumed to be nearly cubic, which is a very structured setting for case analysis and computer search.",
            "<strong>Cycle-length arithmetic.</strong> Results showing that graphs contain cycles of many consecutive lengths, or lengths in many residue classes, might be sharpened to hit a power of 2.",
        ],
        try_it="Draw the Petersen graph (every vertex has degree 3) and find a cycle of length 8. Then try the complete bipartite graph <em>K</em>₃,₃, which has cycles of length 4 immediately. Can you design a degree-3 graph whose shortest cycle has length 5 and that avoids length 8?",
    ),
    dict(
        slug="second-neighborhood", cat="graph-theory", pick=False,
        title="Seymour's Second Neighborhood Conjecture",
        short="Imagine a social network where \"follows\" goes one way and nobody follows each other back. Is there always someone whose followers-of-followers (people two steps away who aren't already direct followers) are at least as many as their direct followers?",
        short_status=None,
        statement="In every oriented graph (a directed graph with no 2-cycles), some vertex <em>v</em> has at least as many vertices at distance exactly 2 as at distance 1: |<em>N</em>⁺⁺(<em>v</em>)| ≥ |<em>N</em>⁺(<em>v</em>)|.",
        facts=[("First posed", "Paul Seymour, 1990"),
               ("Proven for", "Tournaments (1996)"),
               ("Best general ratio", "≈ 0.657 (and a bit more)")],
        importance=[
            "It captures a basic intuition about influence and spread: in a network without mutual links, someone's reach roughly doubles at the second step.",
            "It implies a special case of the <strong>Caccetta–Häggkvist conjecture</strong> on short directed cycles, another major open problem.",
        ],
        status=[
            "Open. Proven for <strong>tournaments</strong>, where every pair of vertices has exactly one arc between them (Fisher, 1996; a simpler proof by Havet and Thomassé, 2000, using \"median orders\"). Also proven for several other dense or structured classes.",
            "In general, Chen, Shen and Yuster (2003) showed some vertex has |<em>N</em>⁺⁺| ≥ γ|<em>N</em>⁺| with γ ≈ 0.657, and there have been small improvements since.",
        ],
        timeline=[
            ("1990", "Seymour poses the conjecture."),
            ("1996", "Fisher proves it for tournaments (Dean's conjecture) using probability."),
            ("2000", "Havet and Thomassé give a combinatorial proof for tournaments via median orders."),
            ("2003", "Chen, Shen and Yuster prove the γ ≈ 0.657 bound for all oriented graphs."),
            ("2010s", "Proven for further classes: dense graphs, graphs with small maximum degree, and others."),
        ],
        approaches=[
            "<strong>Median orders.</strong> Extend the Havet–Thomassé technique from tournaments to graphs with some missing arcs. There has been partial success when few arcs are missing.",
            "<strong>Push the constant.</strong> Improve γ from about 0.66 toward 1 with sharper counting or weighting arguments.",
            "<strong>Minimal counterexamples.</strong> Show a smallest counterexample has no \"sink-like\" vertices and strong regularity, then derive a contradiction.",
        ],
        try_it="Draw 5 people in a circle, each following the next two clockwise. Each person has 2 direct follows and 2 second-step follows, so equality holds. Now remove one arrow and check whether the property still holds.",
    ),
    dict(
        slug="lovasz", cat="graph-theory", pick=False,
        title="Lovász Conjecture",
        short='Call a graph "symmetric" if every vertex looks exactly like every other vertex. Does every connected symmetric graph have a path that visits each vertex exactly once?',
        short_status="Only five connected symmetric graphs are known that have no closed tour through every vertex. The Petersen graph is one of them.",
        statement="Every finite connected vertex-transitive graph has a Hamiltonian path.",
        facts=[("First posed", "László Lovász, 1969"),
               ("Known graphs without a Hamiltonian cycle", "Only 5"),
               ("Cayley graph version", "Also open")],
        importance=[
            "It links <strong>symmetry</strong> (group theory) and <strong>traversal</strong> (Hamiltonicity). Finding Hamiltonian paths is NP-hard in general, so the conjecture says symmetry makes an otherwise hard problem always solvable.",
            "For Cayley graphs of groups, a Hamiltonian cycle lists every element of the group, moving by one generator at a time. <strong>Gray codes</strong>, which list binary strings changing one bit at a time, are the hypercube case.",
        ],
        status=[
            "Open. Only five connected vertex-transitive graphs are known that lack a Hamiltonian <em>cycle</em>: <em>K</em>₂, the Petersen graph, the Coxeter graph, and the two graphs obtained from Petersen and Coxeter by replacing each vertex with a triangle. All five still have Hamiltonian <em>paths</em>.",
            "For <strong>Cayley graphs</strong>, a special kind of vertex-transitive graph, the stronger conjecture is that every connected one on 3 or more vertices has a Hamiltonian cycle. This is proven for abelian groups, for groups of prime-power order (Witte, 1986), and for many groups of special orders.",
            "Dense vertex-transitive graphs are Hamiltonian (Christofides, Hladký and Máthé, 2014). Some experts, notably Babai, suspect the general conjecture may be false.",
        ],
        timeline=[
            ("1953", "Gray codes (patented by Frank Gray) give Hamiltonian cycles on hypercubes."),
            ("1969", "Lovász poses the problem, originally phrased as a challenge to find a counterexample."),
            ("1986", "Witte: Cayley graphs of <em>p</em>-groups have Hamiltonian cycles."),
            ("2014", "Christofides, Hladký and Máthé: dense vertex-transitive graphs are Hamiltonian."),
        ],
        approaches=[
            "<strong>Factor group lemma.</strong> Find a Hamiltonian cycle in a quotient graph and \"lift\" it to the full Cayley graph. This is the main tool in the Cayley case.",
            "<strong>Classify by order.</strong> Prove it for all vertex-transitive graphs whose number of vertices has a given form (<em>p</em>, 2<em>p</em>, <em>p</em><sup>2</sup>, <em>pq</em>, …) and expand the list.",
            "<strong>Search for counterexamples.</strong> Computer searches over small vertex-transitive graphs continue. A sixth non-Hamiltonian example would be big news.",
        ],
        try_it="Draw the 3-dimensional cube (8 vertices, labeled with binary strings 000 to 111). Find a closed tour that changes one bit at a time: 000, 001, 011, 010, 110, 111, 101, 100. That's a Gray code. Then find a path through all 10 vertices of the Petersen graph. It exists, but no matter how you try, you can't close it into a cycle.",
    ),
    dict(
        slug="cycle-double-cover", cat="graph-theory", pick=False,
        title="Cycle Double Cover Conjecture",
        short="Take any graph with no bridge, meaning no single edge whose removal disconnects it. Can you always pick a collection of cycles that covers every edge exactly twice?",
        short_status=None,
        statement="Every bridgeless graph has a collection of cycles such that every edge lies in exactly two of them.",
        facts=[("First posed", "Szekeres (1973), Seymour (1979)"),
               ("Minimal counterexample", "Must be a snark"),
               ("Known", "Covers of every edge exactly 4 or 6 times")],
        importance=[
            "For planar graphs it is easy: the boundaries of the faces cover every edge twice. The conjecture says every bridgeless graph behaves as if it could be drawn on <em>some</em> surface with every face bounded by a cycle. That links it to <strong>surface embeddings</strong>.",
            "It sits in a cluster of central conjectures about <strong>snarks</strong> and <strong>flows</strong>, including Tutte's 5-flow conjecture and the Berge–Fulkerson conjecture. Progress on one often informs the others.",
        ],
        status=[
            "Open. It is true for planar graphs, for cubic graphs with a 3-edge-coloring, and for graphs with a nowhere-zero 4-flow (Jaeger), among others.",
            "A smallest counterexample must be a <strong>snark</strong>: a cubic graph that cannot be 3-edge-colored, like the Petersen graph. It is known that such a counterexample would need very large girth (shortest cycle length).",
            "Weaker versions are proven. Every bridgeless graph has a family of even subgraphs covering each edge exactly 4 times (Bermond, Jackson and Jaeger, 1983) or exactly 6 times (Fan, 1992). \"Exactly twice\" remains open.",
        ],
        timeline=[
            ("1973", "Szekeres poses the problem for cubic graphs."),
            ("1979", "Seymour poses it for all bridgeless graphs."),
            ("1979", "Jaeger shows graphs with a nowhere-zero 4-flow have a cycle double cover."),
            ("1983", "Bermond, Jackson and Jaeger: a 4-fold cover by 7 even subgraphs."),
            ("1992", "Fan: a 6-fold cover by 10 even subgraphs."),
            ("2000s", "Minimal counterexamples are shown to need large girth. Computers verify snarks up to large sizes."),
        ],
        approaches=[
            "<strong>Study snarks.</strong> Since counterexamples must be snarks, understanding their structure is the main line of attack. Computer enumerations of snarks up to 36 or more vertices have found none that fail.",
            "<strong>Flows.</strong> Strengthen flow results (for example, a proof of Tutte's 5-flow conjecture) and relate them to cycle covers.",
            "<strong>Strong embeddings.</strong> Prove that every 2-connected graph embeds in some surface with every face a cycle. That would imply the conjecture.",
        ],
        try_it="The Petersen graph has 15 edges, so a double cover needs total cycle length 30. Find six 5-cycles in the Petersen graph that together use every edge exactly twice. Then do the same for the cube using its 6 faces.",
    ),
    dict(
        slug="total-coloring", cat="graph-theory", pick=False,
        title="Total Coloring Conjecture",
        short="Color both the vertices and the edges of a graph so that touching items always get different colors. If the busiest vertex has Δ edges, you clearly need at least Δ + 1 colors. Is Δ + 2 always enough?",
        short_status=None,
        statement="Every graph with maximum degree Δ has a total coloring (of vertices and edges, where adjacent vertices, adjacent edges, and each vertex with its own edges all get different colors) using at most Δ + 2 colors.",
        facts=[("First posed", "Behzad and Vizing, mid-1960s"),
               ("Proven for", "Δ ≤ 5"),
               ("Best general bound", "Δ + C for a huge constant C")],
        importance=[
            "It unifies the two classical coloring problems. For edges alone, Vizing's theorem says Δ or Δ + 1 colors always suffice. The total coloring conjecture is the natural analogue when vertices and edges are colored together.",
            "Colorings like this model <strong>scheduling</strong> problems where both resources (vertices) and interactions (edges) need time slots that don't clash.",
        ],
        status=[
            "Open. Proven for all graphs with Δ ≤ 5 (Rosenfeld and Vijayaditya for Δ = 3; Kostochka for Δ = 4 and 5). For planar graphs it is proven for every Δ except Δ = 6.",
            "Molloy and Reed (1998) proved that Δ + <em>C</em> colors always suffice, for an absolute constant <em>C</em>. Their <em>C</em> was astronomically large (around 10²⁶), but it is a constant.",
            "It is known exactly for complete graphs, complete bipartite graphs, cycles and many other families.",
        ],
        timeline=[
            ("1964", "Vizing proves edge colorings need only Δ or Δ + 1 colors."),
            ("1965", "Behzad (and Vizing independently) conjectures Δ + 2 colors suffice for total coloring."),
            ("1971", "Rosenfeld and Vijayaditya prove it for Δ = 3."),
            ("1977–96", "Kostochka proves it for Δ = 4 and Δ = 5."),
            ("1998", "Molloy and Reed: Δ + <em>C</em> colors suffice, using the probabilistic method."),
            ("1990s–2000s", "Planar graphs settled for Δ ≥ 7 using the discharging method."),
        ],
        approaches=[
            "<strong>Probabilistic method.</strong> Refine the Molloy–Reed argument (random coloring plus the Lovász Local Lemma) to shrink the constant toward 2.",
            "<strong>Discharging for planar graphs.</strong> The planar Δ = 6 case is the last one left, and fits the discharging technique used for the Four Color Theorem.",
            "<strong>Reduce to edge coloring.</strong> Total coloring a graph is the same as vertex coloring its \"total graph\". Use structural results about those graphs, or embed the problem into an edge-coloring problem on a larger graph.",
        ],
        try_it="Totally color a triangle: 3 vertices and 3 edges, with Δ = 2. You can do it with Δ + 1 = 3 colors (hint: give each edge the color of the vertex opposite it). Then try the complete graph <em>K</em>₄ (Δ = 3). Can you manage with 4 colors, or do you need Δ + 2 = 5?",
    ),
]
